### ISSUE TITLE
将人工智能应用于棋类游戏开发中的一般步骤

### ISSUE THREAD

**Issue by Jeff-Tian** [apachecn/awesome-article-recomm#3]
博文地址： https://short.js.org/AnMk0OAz
是否为个人原创： 是
投稿推荐语： 机器学习入门，手把手教你写一个智能版三子棋程序。
原作者信息(选填)：Jeff-Tian
原始发布平台： https://tictactoe.js.org
联系方式：jeff.tian@outlook.com

**Comment by Watermelon233** [comment]
收到 今日头条推送~ Awesome！
