### ISSUE TITLE
北美 2020 summer internship 汇总

### ISSUE THREAD

**Issue by FoxerLee** [apachecn/awesome-article-recomm#5]
- 博文地址（其实是GitHub仓库）：https://github.com/elaine-zheng/summer2020internships
- 非本人原创
- 整理了当前北美大量的实习岗位，主要为 SWE 相关，可以按照这个表一个一个投 :)，并且仍然在实时更新
- 原作者：[elaine-zheng](https://github.com/elaine-zheng)

**Comment by wizardforcel** [comment]
将会加到学习资料的“其他”一节，谢谢你的投稿
